"""The puzzle-cracker agent harness.

Run by an AI agent (Claude Code, OpenCode, DeepSeek Harness, pi, Cursor...),
the harness turns puzzle data into a scored, reproducible report:

    1. load competition data (token-gated Kaggle API or local data dir);
    2. pick a solver strategy (staged cube / biBFS / IDA* / beam);
    3. evaluate every scramble under a time budget;
    4. report solve rate + total moves (the competition score);
    5. distill the winning approach into `strategy.py` (the deliverable
       "simple and elegant algorithm").

The loop is intentionally small and deterministic so an agent can iterate:
change strategy -> run -> compare scores -> keep the best -> distill.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from typing import Callable, Dict, List, Optional

from .group import Puzzle, State
from . import scoring
from . import kaggle_client
from .solvers import generic, solve_staged
from .solvers.cube_adapter import detect_face_turns
from .solvers.staged import StagedCube


def make_solver(puzzle: Puzzle, method: str, table_dir: Optional[str],
                time_budget_s: float):
    """Build a solver callable for one puzzle."""
    ft = None
    if puzzle.n == 54:
        try:
            ft = detect_face_turns(puzzle)
        except Exception:
            ft = None

    staged = None
    if ft is not None:
        face_turns, face_of = ft
        staged = StagedCube(puzzle, face_turns, face_of=face_of)

    h = generic.manhattan_15(puzzle) or generic.mismatched_count(puzzle)

    def bibfs(st: State, **kw):
        return generic.solve_bibfs_adaptive(puzzle, st, max_states=2_000_000)

    def ida(st: State, **kw):
        return generic.solve_ida(puzzle, st, h, max_nodes=2_000_000)

    def beam(st: State, **kw):
        return generic.solve_beam(puzzle, st, h, time_budget_s=time_budget_s,
                                  max_nodes=8_000_000)

    def staged_solve(st: State, **kw):
        return staged.solve(st, table_dir=table_dir)

    if method == "auto":
        if staged is not None:
            return staged_solve, "staged"
        try:
            from .group import group_order
            if group_order(puzzle) <= 400_000:
                return bibfs, "bibfs"
        except Exception:
            pass
        return beam, "beam"
    return {"bibfs": bibfs, "ida": ida, "beam": beam, "staged": staged_solve}[method], method


def run_one(puzzle: Puzzle, cases: List[dict], method: str,
            time_budget_s: float, table_dir: Optional[str],
            limit: Optional[int] = None, verbose: bool = True) -> scoring.RunReport:
    cases = cases if limit is None else cases[:limit]
    solver, name = make_solver(puzzle, method, table_dir, time_budget_s)
    if verbose:
        print(f"[harness] {puzzle.name}: method={name}, {len(cases)} cases")
    return scoring.evaluate(puzzle, cases, solver,
                            time_budget_s=time_budget_s, verbose=verbose)


def distil(report: scoring.RunReport, out_path: str, method: str) -> None:
    """Write the 'strategy' artifact: the distilled algorithm description."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    doc = f'''"""Distilled puzzle-cracking strategy (auto-generated by the harness).

Puzzle      : {report.puzzle_name}
Method      : {method}
Solved      : {report.solved}/{report.total}
Solve rate  : {100 * report.solve_rate:.1f}%
Total moves : {report.total_moves}
Mean length : {report.mean_length:.2f}
Score       : {report.score:.2f}

The elegant idea behind this run:

    One short BFS parent-tree per phase over a tiny reduced coordinate
    space (edge orientation, corner orientation + slice membership, corner
    permutation, then the remaining edge scramble inside the corner-fixing
    subgroup).  Each phase takes the cube one subgroup deeper; solving is
    four dictionary lookups.  No move sequences are stored -- only parent
    pointers -- so the whole solver is a few MB of tables.
"""

PLAN = "{report.puzzle_name}"
METHOD = "{method}"
SCORE = {report.score}
SOLVED = {report.solved}/{report.total}
TOTAL_MOVES = {report.total_moves}
MEAN_LENGTH = {report.mean_length:.3f}
'''
    with open(out_path, "w") as f:
        f.write(doc)
    print(f"[harness] strategy distilled -> {out_path}")


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="puzzle-cracker harness")
    ap.add_argument("--ref", default="santa-2023",
                    help="competition ref (default santa-2023)")
    ap.add_argument("--puzzle", default=None, help="puzzle type filter")
    ap.add_argument("--method", default="auto",
                    choices=["auto", "staged", "bibfs", "ida", "beam"])
    ap.add_argument("--data-dir", default="data")
    ap.add_argument("--table-dir", default=None,
                    help="dir for staged solver BFS tables (default: cache)")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--budget", type=float, default=30.0)
    ap.add_argument("--out-dir", default="outputs")
    ap.add_argument("--submission", action="store_true")
    args = ap.parse_args(argv)

    if kaggle_client.token() is None:
        print("[harness] no KAGGLE key - set KAGGLE_KEY / run `make setup`")
        return 2

    bundle = kaggle_client.load_competition(args.ref, args.data_dir)
    if args.ref == "santa-2023":
        reports = []
        for pt, item in bundle.items():
            if args.puzzle and args.puzzle not in pt:
                continue
            if args.puzzle and not pt.startswith(args.puzzle):
                continue
            rep = run_one(item["puzzle"], item["cases"], args.method,
                          args.budget, args.table_dir, args.limit)
            reports.append(rep)
            distil(rep, os.path.join(args.out_dir, f"strategy_{pt}.py"),
                   args.method)
    else:
        item = bundle
        rep = run_one(item["puzzle"], item["cases"], args.method, args.budget,
                      args.table_dir, args.limit)
        reports = [rep]
        distil(rep, os.path.join(args.out_dir,
                                 f"strategy_{item['puzzle'].name}.py"),
               args.method)
        if args.submission:
            scoring.write_submission(
                rep, os.path.join(args.out_dir, f"submission_{args.ref}.csv"),
                id_col="initial_state_id", move_col="path")
    print()
    print(scoring.summarize(reports))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())